### ISSUE TITLE
Suggest merging your list into existing, official sources

### ISSUE THREAD

**Issue by stevepiercy** [uralbash/awesome-pyramid#1]
Suggest merging your list into existing, official resources or community resources.

Official
http://trypyramid.com/
http://docs.pylonsproject.org/projects/pyramid-tutorials/en/latest/
http://docs.pylonsproject.org/en/latest/docs/pyramid.html#supported-add-ons

Community
http://docs.pylonsproject.org/projects/pyramid-cookbook/en/latest/

**Comment by uralbash** [comment]
@stevepiercy I created awesome-pyramid version on [readthedocs](http://awesome-pyramid.readthedocs.org). This can replace github WiKi ([1](https://github.com/Pylons/pyramid/wiki/Companies-and-organizations-that-use-Pyramid), [2](https://github.com/Pylons/pyramid/wiki/Projects-that-use-Pyramid)) and makes it easy to copy data in the official documentation (Just configure your conf.py).

**Comment by stevepiercy** [comment]
The plan is to replace those wiki pages with [notaliens.com](http://notaliens.com) when that project is deployed.

**Comment by stevepiercy** [comment]
Closing this issue, as I've deployed these items to trypyramid.com.

I'm also watching this repo, so I can copy new items to trypyramid.com. Individuals can now submit PRs to master branch to add their listings. https://github.com/Pylons/trypyramid.com
